//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fianzapp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int id_admin { get; set; }
        public string nombre_administrador { get; set; }
        public string documento_administrador { get; set; }
        public string correo_administrador { get; set; }
        public string usuario_administrador { get; set; }
        public string contrasena_administrador { get; set; }
        public int id_rol { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Proceso Proceso { get; set; }
    }
}
