//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fianzapp.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FianzappEntities : DbContext
    {
        public FianzappEntities()
            : base("name=FianzappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Demandado> Demandado { get; set; }
        public virtual DbSet<Estado_Proceso> Estado_Proceso { get; set; }
        public virtual DbSet<Estado_Seguimiento> Estado_Seguimiento { get; set; }
        public virtual DbSet<Proceso> Proceso { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Seguimiento_Proceso> Seguimiento_Proceso { get; set; }
    }
}
